### ISSUE TITLE
At WebGL Build Video is not working....

### ISSUE THREAD

**Issue by satyagames** [luzan/UnityVideoPlayer#1]
i Build a WebGL output.... But video is not playing ....
Can you know what is the problem ?

**Comment by luzan** [comment]
Are you getting any sorts of error message? And is the project same as in the repository or have you changed some codes?

**Comment by luzan** [comment]
BTW if you are trying to play VideoClip then it is not supported for WebGL, only videos from URL will be played.

**Comment by satyagames** [comment]
It is not played even by using URL... (WebGL out put)

**Comment by luzan** [comment]
Actually, this **tutorial project was build for Android not for WebGL**. I cannot solve your issue on WebGL. Please visit this forum thread https://forum.unity3d.com/threads/videoplayer-webgl-url-not-working.467391/ if that doesnot fix your problem you can create new thread on Unity Forum.

**Comment by satyagames** [comment]
O.K
