### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by hackerenherbe** [luzan/UnityVideoPlayer#2]
Good afternoon Luzan,

First i would like to thank you for your work on this tutorial.

I try to make my own video player in unity (Unity 5.6.1f1) for a simple project. I have sadly an error, and don't know why. Indeed I did everything as you explain it in your tutorial but I'm faced with a NullreferenceException type error : 

_NullReferenceException: Object reference not set to an instance of an object
StreamVideoPraxies.PlayPause () (at Assets/StreamVideoPraxies.cs:95)
UnityEngine.Events.InvokableCall.Invoke (System.Object[] args) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:154)
UnityEngine.Events.InvokableCallList.Invoke (System.Object[] parameters) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:637)_

The code making the error is in StreamVideo.cs : 
`
public RawImage videoPraxie;
    public GameObject playIcon;

    public VideoClip videoToPlay;

    private VideoPlayer videoPlayer;
    private VideoSource videoSource;

    private AudioSource audioSource;
    private bool isPaused = false;
    private bool firstRun = true;

    IEnumerator playVideo()
    {
        playIcon.SetActive(false);
        firstRun = false;

        videoPlayer = gameObject.AddComponent<VideoPlayer>();

        audioSource = gameObject.AddComponent<AudioSource>();

        videoPlayer.playOnAwake = false;
        audioSource.playOnAwake = false;
        audioSource.Pause();

        videoPlayer.source = VideoSource.VideoClip;

        videoPlayer.audioOutputMode = VideoAudioOutputMode.AudioSource;

        //Assign the Audio from Video to AudioSource to be played
        videoPlayer.EnableAudioTrack(0, true);
        videoPlayer.SetTargetAudioSource(0, audioSource);

        videoPlayer.clip = videoToPlay;
        videoPlayer.Prepare();

        WaitForSeconds waitTime = new WaitForSeconds(1);
        while (!videoPlayer.isPrepared)
        {
            Debug.Log("Preparing Video");
            //Prepare/Wait for 5 sceonds only
            yield return waitTime;
            //Break out of the while loop after 5 seconds wait
            break;
        }

        Debug.Log("Done Preparing Video");

        videoPraxie.texture = videoPlayer.texture;

        videoPlayer.Play();

        audioSource.Play();

        Debug.Log("Playing Video");
        while (videoPlayer.isPlaying)
        {
            Debug.LogWarning("Video Time: " + Mathf.FloorToInt((float)videoPlayer.time));
            yield return null;
        }

        Debug.Log("Done Playing Video");
    }

    public void PlayPause()
    {
        if (firstRun && !isPaused)
        {
            Debug.Log("===========HERE MY BUG=================================");
            videoPlayer.Pause();
            Debug.Log("===========NEVER SEE THIS BECAUSE PREVIOUS LINE CRASH==========");
            audioSource.Pause();
            playIcon.SetActive(false);
            isPaused = true;
        } else if(!firstRun && isPaused)
        {
            videoPlayer.Play();
            audioSource.Play();
            playIcon.SetActive(false);
            isPaused = false;
        } else
        {
            StartCoroutine(playVideo());
        }
    }
}`

I put a comment where it seems to crash. I don't find why it doesn't work...Do you have any idea of why does it crash ?
**Assumptions :** 
- My script is called : StreamVideoPraxies.
- My RawImage is called: videoPraxie

Thank you in advance,
NetKiD

P.S = Thank you again for your video and tutorial :)

**Comment by luzan** [comment]
Thanks for using the tutorial as reference. I am glad that you tried it. Sorry to hear that you had problem with the code. `NullReferenceException` is a very common error in OOP, but I didn't had this problem with the code in my end. Only thing that I could do is describe the nature of the error, and say what might be causing the problem.

**Cause of NullReferenceException**

The runtime throwing a `NullReferenceException `always means the same thing: you are trying to use a reference. The reference is not initialized (or it was once initialized, but is _no longer initialized_).

This means the reference is `null`, and you cannot access members through a `null `reference. In your case it might be `videoPlayer`, you'll have to check if the `videoPlayer `is initialized or not, even if it is initialized at the start of execution it might no longer be initialized inside the `PlayPause()` method.

Reference[https://stackoverflow.com/a/4660186/1939163](: https://stackoverflow.com/a/4660186/1939163)

**Comment by UneebKari** [comment]
@hqcker did you assign following in the inspector from the hierarchy?
(RawImage) videoPraxie
(GameObject) playIcon

**Comment by hackerenherbe** [comment]
Yes, Everything is OK now. I make a new project, and copy paste your script. It work now.
Thank you for your help ;)
